language: node_js
cache: npm

matrix:
  include:
    - os: linux
      dist: bionic
      node_js: "10"
    - os: osx
      osx_image: xcode11
      node_js: "10"
    - os: windows
      node_js: "10"
    - os: linux
      dist: bionic
      node_js: "11"
    - os: osx
      osx_image: xcode11
      node_js: "11"
    - os: windows
      node_js: "11"
    - os: linux
      dist: bionic
      node_js: "12"
    - os: osx
      osx_image: xcode11
      node_js: "12"
    - os: windows
      node_js: "12"

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: script
    skip_cleanup: true
    script: npm publish --access public
    on:
      tags: true
      os: 'linux'
      node_js: '12'
